update CFP / ticket info
GoCon/2022spring pull request #2
Opened 2021-09-30 12:32 UTC by syumai

* CFP / チケットの情報の更新
  - 日程を埋めた
  - CFPのURLを正しいものに更新した
  - `in Tokyo` の表記を取った
* スポンサーシップのプランは公開がまだなので非表示にした

## スクショ

### 日本語

![スクリーンショット 2021-09-30 21 29 34](https://user-images.githubusercontent.com/6882878/135455349-65d0c9c7-40cd-4312-96e9-c43d5990d5f2.png)

### 英語

![スクリーンショット 2021-09-30 21 29 09](https://user-images.githubusercontent.com/6882878/135455393-8c2eed50-b1d1-416a-8626-8a459e1b5871.png)

2021-09-30 23:15 UTC, quwen approved these changes
LGTM!!!

2021-10-01 01:04 UTC, tenntenn approved these changes
LGTM

2021-10-01 01:05 UTC, tenntenn commented
@syumai 
あ！LGTMしちゃったけど、Call for PaperはCall for Proposalが正しいです！

2021-10-01 01:06 UTC, tenntenn requested changes
Call for Paper → Call for Proposal

2021-10-01 01:08 UTC, syumai commented
@tenntenn 修正しました！
![スクリーンショット 2021-10-01 10 07 24](https://user-images.githubusercontent.com/6882878/135550450-ba8b66c7-27c4-4f74-b5e0-55bb8e74a8e7.png)

2021-10-03 05:43 UTC, merged